spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Quizzard?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&serverTimezone=EST
    username: root
    password: NC$tate20192023
    hikari:
      idleTimeout: 500
      connectionTimeout: 15000 
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

server:
  port: 8080
